name: 'Development Build'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS Intel (x86_64)
          - platform: macos-latest
            target: x86_64-apple-darwin
            arch: x64
            os_name: macos-intel
          # macOS Apple Silicon (ARM64)
          - platform: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
            os_name: macos-arm64
          # Linux x86_64
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x64
            os_name: linux-x64
          # Linux ARM64 (disabled for dev builds to save time)
          # - platform: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   arch: arm64
          #   os_name: linux-arm64
          # Windows x86_64
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x64
            os_name: windows-x64
          # Windows ARM64 (disabled for dev builds to save time)
          # - platform: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   arch: arm64
          #   os_name: windows-arm64

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run tauri build -- --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hosts-editor-${{ matrix.os_name }}-dev
          path: |
            src-tauri/target/${{ matrix.target }}/release/hosts-editor*
            src-tauri/target/${{ matrix.target }}/release/*.exe
            src-tauri/target/${{ matrix.target }}/release/bundle/**/*
          retention-days: 7